version: '2'
services:
  web:
    image: gitea/gitea:1.8.3
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
      - "30:30"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea12345
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=Juandi@04201990!
    volumes:
      - ./db/:/var/lib/mysql